export default {
  primary: '#F05035',
  primaryLabel: '#FFFFFF',
  primaryAlt: '#f37762',
  secondary: '#55cbb7',
  secondaryLabel: '#B6B6B6',
  thirdLabel: '#D8D8D8',
  text: '#585858',
  secondaryText: '#D1D1D6', // Inactive tabs, placeholders
  icon: '#000000',
  background: '#FFFFFF',
  secondaryBackground: '#F7F8FA',
  loginBackground: '#0066FF',
  loadingIndicator: '#fff',
  inputBackground: '#F3FBF9',
  iconBackground: '#E58E8E',
  border: '#EAECEF',
  secondaryBorder: '#F0F0F0',
  inverted: '#FFFFFF',
  negative: '#FF3B30',
  disabled: '#D8D8D8',
  facebook: '#3C5A99',
  shadow: '#efefef',
};
